version: '3'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=reallyStrongPwd123
    ports:
      - '1433:1433'
      
  web:
    image: netflicks:1
    depends_on:
      - database
    ports:
      - '90:80'
    volumes:
      - ./contrast-data:/opt/contrast/
    environment:
      - ConnectionStrings__DotNetFlicksConnection=Server=tcp:database,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;
      
volumes:
  mysql-data:
